version: '3.9'
services:
  api-server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mymongo
    env_file: .env
    environment:
      - MONGODB_URL=mongodb://localhost/maptrip
      - JWT_SECRET=thisismyS+cret
  mymongo:
    image: mymongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cos4105
      - MONGO_INITDB_ROOT_PASSWORD=cos4105
